version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - unused
    - ineffassign
    - gocritic
  exclusions:
    rules:
      - linters: [misspell]
        path: _test\.go

linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - truncateCmp
      - unnamedResult

formatters:
  enable:
    - gofmt
    - goimports

output:
  sort-order:
    - file
